### ISSUE TITLE
License

### ISSUE THREAD

**Issue by anlumo** [danielstern/MagicCircles#1]
This is awesome!

Please provide a license for this, so somebody else can use it!

**Comment by danielstern** [comment]
Hey Anlumo!

Thank you for your excellent feedback!

I will add an official license to the file, in the mean time you can go ahead, because the license is 

Attribution 
CC BY

Meaning you can change, modify, tweak and redistribute, but please provide credit where appropriate!

**Comment by anlumo** [comment]
Thank you!

Note that it's not recommended to use CC for software (see the [Creative Commons FAQ](http://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F)), except for CC0. Maybe the [3-clause BSD](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_.28.22Revised_BSD_License.22.2C_.22New_BSD_License.22.2C_or_.22Modified_BSD_License.22.29) would be better?

**Comment by danielstern** [comment]
I've had a look and that license looks fairly solid, so I will attach that one to the project.

Cheers,
DS

**Comment by danielstern** [comment]
The license has been officially attached. Cheers!

**Comment by anlumo** [comment]
Great, thank you!
