### ISSUE TITLE
Method for checking text length

### ISSUE THREAD

**Issue by anlumo** [danielstern/MagicCircles#3]
When I add text to the circle, it might cut off because it's too long, or might leave a lot of whitespace, because it's too short for the specific radius.

It would be great if there were a function to check for that. It could be a function that gets passed the same parameters as the text function, and returns a percentage, where > 100% would be too long and < 100% would leave whitespace.

**Comment by danielstern** [comment]
Hey Anlumo.

I thought this was a solid idea, so I've gone ahead and implemented it.

https://github.com/danielstern/MagicCircles#autofit

Cheers!

**Comment by anlumo** [comment]
Yay!
